name: Merged.

on:
  pull_request:
    types:
      - closed
    branches:
      - release

jobs:
  output:
    name: Output
    runs-on: ubuntu-latest
    steps:
    - name: Build and Push to Viadock
      run: |
        echo ${{ github.head_ref }}
        echo "VERSION=$(echo ${{ github.head_ref }} | sed 's/pr/kitten/')" >> $GITHUB_ENV
        echo version was ${{env.VERSION}}
        docker build -t jonny7/a:${{ env.VERSION }} .
