name: Merged.

on:
  pull_request:
    types:
      - closed
    branches:
      - release

jobs:
  release:
    name: Release Docker Image
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Pull source instead of buildx
        uses: actions/checkout@v2
  output:
    name: Output of event
    runs-on: ubuntu-latest
    steps:
      - name: Do stuff
        env:
          TAG: release/1.19.0
        run: |
          echo the merged branch was ${{ github.ref }}
          echo tag=$(echo ${{ github.ref }} | sed 's/release\///')
          echo the new tag var is $tag
