name: Merged.

on:
  pull_request:
    types:
      - closed
    branches:
      - release

jobs:
  output:
    name: Output
    runs-on: ubuntu-latest
    steps:
    - name: Set tag
      id: tag-step
      run: |
        echo "::set-output name=TAG::$(echo ${{ github.head_ref }} | sed 's/pr/kitten/')"
        
    - name: Build and Push to Viadock
      run: |
        echo value was "${{ steps.tag-step.outputs.TAG }}"
        docker build -t jonny7/a:${{ steps.tag-step.outputs.TAG }} .
      env:
        NEW_VERSION: ${{ env.VERSION }}
