name: Merged.

on:
  pull_request:
    types:
      - closed
    branches:
      - release

jobs:
  output:
    name: Output
    runs-on: ubuntu-latest
    steps:
    - name: Build and Push to Viadock
      run: |
        echo "VERSION2=$(echo ${{ github.head_ref }} | sed 's/pr/kitten/')"
        echo ${{ env.VERSION2 }}
        echo "VERSION3=something" >> $GITHUB_ENV
        echo ${{ env.VERSION3 }}
        echo ${{ github.head_ref }}
        echo "VERSION=$(echo ${{ github.head_ref }} | sed 's/pr/kitten/')" >> $GITHUB_ENV
        echo version was ${{env.VERSION}}
        echo $NEW_VERSION
        docker build -t jonny7/a:${{ env.VERSION }} .
      env:
        NEW_VERSION: ${{ env.VERSION }}
