name: Merged.

env:
  COMPUTED: echo ${{ github.head_ref }} | sed 's/pr/kitten/'

on:
  pull_request:
    types:
      - closed
    branches:
      - release

jobs:
  output:
    name: Output
    runs-on: ubuntu-latest
    steps:
    - name: Build and Push to Viadock
      run: |
        echo ${{ github.head_ref }} | sed 's/pr/kitten/'
        echo version was $VERSION
        docker build -t jonny7/a:$VERSION .
      env:
        VERSION: ${{ env.COMPUTED }}
