# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  skip-pipeline:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repos
      uses: actions/checkout@v2
    
    - name: Build file
      run: |
        cat <<\EOT >nginx.conf
        port: 8000
        host: 0.0.0.0
        EOT
        cat nginx.conf
    
    - name: Do docker stuff with volume
      run: |
        docker-compose build
        docker-compose up --abort-on-container-exit
