# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  skip-pipeline:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.set-skip.outputs.skip || false }}
    steps:
      - name: Set skip output var
        id: set-skip
        if: contains(github.event.pull_request.labels.*.name, 'skip-ci')
        run: echo "::set-output name=skip::true"

  integration_tests:
    runs-on: ubuntu-latest
    needs: skip-pipeline
    if: needs.skip-pipeline.outputs.skip == 'false'
    steps:
    - name: Getting skip output var value
      run: echo ${{needs.skip-pipeline.outputs.skip}}
